name: Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Create documentation
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          if [ -f "willsx/build-docs.php" ]; then
            echo "Found build-docs.php in willsx directory"
            php willsx/build-docs.php
          elif [ -f "build-docs.php" ]; then
            echo "Found build-docs.php in root directory"
            php build-docs.php
          else
            echo "Could not find build-docs.php"
            find . -name "*.php" | sort
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'willsx/build/docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
